### ISSUE TITLE
Production builds and container deployment

### ISSUE THREAD

**Issue by howamith** [cron-mon-io/cron-mon-app#8]
Will need to serve the application up via nginx or similar. See https://github.com/cron-mon-io/cron-mon/issues/20 for potential gotcha.

Push the containers to GitHub Container Registry (see [this](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry)). Might want a release based pipeline for this?

**Comment by howamith** [comment]
It's Vue 2 which is legacy but this looks helpful for getting a single container serving up the app via nginx https://v2.vuejs.org/v2/cookbook/dockerize-vuejs-app

**Comment by NWBY** [comment]
@howamith since this is a Vite app it could also be worth looking at Caddy to just serve the static files after running `npm run build`. Example Caddyfile would look like this:
```
# Set the port or domain below for automatic SSL
:80, :443, example.com {
	# access logs
	log {
		format json # set access log format to json mode
	}

	# serve from the 'dist' folder (Vite builds into the 'dist' folder)
	root * dist

	# enable gzipping responses
	encode gzip

	# serve files from 'dist'
	file_server

	# if path doesn't exist, redirect it to 'index.html' for client side routing
	try_files {path} /index.html
}
```

**Comment by howamith** [comment]
Thanks for the suggestion! I'd not heard of Caddy but it looks awesome, will definitely have a play with it.

The biggest unknown for me here currently is runtime configuration, since the idea is to just build and push container images to GitHub Container Registry, and let developers use it to host and run it where ever and however they wish. I've already got this working for the backend, and runtime configuration for things like the DB connection string are handled via environment variables. Since this is a Vue x Vite app, environment variables are only available at build time, and with my limited frontend experience I'm not sure how this sort of thing is typically handled.

Only ideas I have so far is to just expect devs to mount a JSON file in an expected directory for us to read, or perhaps something with config maps? If you have any suggestions on this I'm all ears!

**Comment by howamith** [comment]
Thanks @NWBY, `import-meta-env` looks pretty promising!

Defaults just won't work because users could expose the API on any domain/ host they choose, or the Postgres DB on any domain/ host - or once I've finished the auth work, the Keycloak server on any domain/ host, as well as the realm and client they wish to use.

Letting users build from source is already an option since the projects' public, but being able to pull from a container registry makes everything easier (i.e you don't have to clone the project and build it yourself, just `docker pull ghcr.io/cron-mon-io/cron-mon-app:0.1.0` and voila) and also unlocks some possibilities (like being able to specify a Docker image path in the likes of Docker Compose and HelmRelease).

The JSON/ConfigMap approach would work at runtime by having the app fetch the JSON file via AJAX. Looking at `import-meta-env` though, I'm guessing it's doing something similar to this but in a much more complete and robust way, so I'll definitely be opting for that route - thanks again!
